namespace Ipocom.SonyMotionFormat
{
    public enum Bones
    {
        root,
        torso_1,
        torso_2,
        torso_3,
        torso_4,
        torso_5,
        torso_6,
        torso_7,
        neck_1,
        neck_2,
        head,
        l_shoulder,
        l_up_arm,
        l_low_arm,
        l_hand,
        r_shoulder,
        r_up_arm,
        r_low_arm,
        r_hand,
        l_up_leg,
        l_low_leg,
        l_foot,
        l_toes,
        r_up_leg,
        r_low_leg,
        r_foot,
        r_toes,
    }
}
